###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
 
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
      networks:
        - web-db-net

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

      networks:
        - web-db-net
  
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8081:80
      environment:
        - PMA_ARBITRARY=1

    webserver:
      image: nginx:alpine
      container_name: phpdocker-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8005:80"
      links:
       - php-fpm
      networks:
        - web-db-net
    
    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpdocker-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - web-db-net

networks:
    web-db-net:
  

    
